// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel() {
  return window['go']['main']['App']['Cancel']();
}

export function GetCPUCount() {
  return window['go']['main']['App']['GetCPUCount']();
}

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetCategoryColors() {
  return window['go']['main']['App']['GetCategoryColors']();
}

export function GetProgress() {
  return window['go']['main']['App']['GetProgress']();
}

export function IsRunning() {
  return window['go']['main']['App']['IsRunning']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function StartOrganize(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartOrganize'](arg1, arg2, arg3, arg4);
}
