// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {organizer} from '../models';

export function Cancel():Promise<void>;

export function GetCPUCount():Promise<number>;

export function GetCategories():Promise<Record<string, Array<string>>>;

export function GetCategoryColors():Promise<Record<string, string>>;

export function GetProgress():Promise<organizer.ProgressEvent>;

export function IsRunning():Promise<boolean>;

export function SelectDirectory():Promise<string>;

export function StartOrganize(arg1:string,arg2:boolean,arg3:number,arg4:string):Promise<organizer.Summary>;
